In [7]:
# This section recommends: [BFGS, Powell, Nelder-Mead]
# https://scipy-lectures.org/advanced/mathematical_optimization/index.html#practical-guide-to-optimization-with-scipy
from scipy.optimize import minimize

fun = lambda x: (x[0] - 1)**2 + (x[1] - 2.5)**2
# Limits to x[0], x[1]
bnds = ((0, None), (0, None))
init_cond = (2, 0)

for method in ['BFGS', 'Powell', 'Nelder-Mead']:
  res = minimize(fun, init_cond, method=method, bounds=bnds)
  print("-------------------------")
  print("Method: " + method)
  print(res)
  # Noteworthy: res.success, res.x, res.fun
  print("Success = %s, optimized result = %s, best parameter values = %s" %
       (res.success, res.fun, res.x))

-------------------------
Method: BFGS
      fun: 1.0075886211189263e-15
 hess_inv: array([[0.93103449, 0.17241379],
       [0.17241379, 0.56896552]])
      jac: array([-4.85836291e-08,  1.47117323e-08])
  message: 'Optimization terminated successfully.'
     nfev: 12
      nit: 2
     njev: 3
   status: 0
  success: True
        x: array([0.99999997, 2.5       ])
Success = True, optimized result = 1.0075886211189263e-15, best parameter values = [0.99999997 2.5       ]
-------------------------
Method: Powell
   direc: array([[1., 0.],
       [0., 1.]])
     fun: 4.930380657631324e-32
 message: 'Optimization terminated successfully.'
    nfev: 36
     nit: 2
  status: 0
 success: True
       x: array([1. , 2.5])
Success = True, optimized result = 4.930380657631324e-32, best parameter values = [1.  2.5]
-------------------------
Method: Nelder-Mead
 final_simplex: (array([[1.00001833, 2.49997712],
       [0.9999936 , 2.50003761],
       [1.00005617, 2.50000797]]), array([8.59734870e-10,

/home/stephen/anaconda3/lib/python3.7/site-packages/scipy/optimize/_minimize.py:522: RuntimeWarning: Method BFGS cannot handle constraints nor bounds.
  RuntimeWarning)
/home/stephen/anaconda3/lib/python3.7/site-packages/scipy/optimize/_minimize.py:522: RuntimeWarning: Method Powell cannot handle constraints nor bounds.
  RuntimeWarning)
/home/stephen/anaconda3/lib/python3.7/site-packages/scipy/optimize/_minimize.py:522: RuntimeWarning: Method Nelder-Mead cannot handle constraints nor bounds.
  RuntimeWarning)


In [1]:
import connectomes
import numpy as np

Gg = np.array([[0, 8, 5],
               [8, 0, 2],
               [5, 2, 0]])
Gs = np.array([[0, 4, 5],
               [1, 0, 6],
               [2, 3, 0]])
N = 3
compact = connectomes.model_to_compact_param(Gg, Gs, N)
uncompacted = connectomes.compact_to_model_param(compact, N)

In [2]:
compact

array([8, 5, 2, 1, 2, 3, 4, 5, 6])

In [3]:
uncompacted

(array([[0., 8., 5.],
        [8., 0., 2.],
        [5., 2., 0.]]),
 array([[0., 4., 5.],
        [1., 0., 6.],
        [2., 3., 0.]]))

In [4]:
connectomes.get_random_connectome(3)

TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions