In [ ]:
# This section recommends: [BFGS, Powell, Nelder-Mead]
# https://scipy-lectures.org/advanced/mathematical_optimization/index.html#practical-guide-to-optimization-with-scipy
from scipy.optimize import minimize

fun = lambda x: (x[0] - 1)**2 + (x[1] - 2.5)**2
# Limits to x[0], x[1]
bnds = ((0, None), (0, None))
init_cond = (2, 0)

for method in ['BFGS', 'Powell', 'Nelder-Mead']:
  res = minimize(fun, init_cond, method=method, bounds=bnds)
  print("-------------------------")
  print("Method: " + method)
  print(res)
  # Noteworthy: res.success, res.x, res.fun
  print("Success = %s, optimized result = %s, best parameter values = %s" %
       (res.success, res.fun, res.x))

In [4]:
import connectomes
import numpy as np

Gg = np.array([[0, 8, 5],
               [8, 0, 2],
               [5, 2, 0]])
Gs = np.array([[0, 4, 5],
               [1, 0, 6],
               [2, 3, 0]])
N = 3
compact = connectomes.model_to_compact_param(Gg, Gs, N)
uncompacted = connectomes.compact_to_model_param(compact, N)

In [5]:
compact

array([8, 5, 2, 1, 2, 3, 4, 5, 6])

In [6]:
uncompacted

(array([[0., 8., 5.],
        [8., 0., 2.],
        [5., 2., 0.]]),
 array([[0., 4., 5.],
        [1., 0., 6.],
        [2., 3., 0.]]))